server:
  port: 1912
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/01-warehouse-management"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false


